#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
"""
newpost.py — scaffold and check blog posts. Runs, does its job, exits.

    uv run newpost.py new "A join that returned zero rows"
    uv run newpost.py new "What I got wrong about renting" -c notes -t housing,tampa
    uv run newpost.py check

Nothing stays running. There's no server here on purpose: VS Code Live Server
already previews the site, and VS Code already edits the markdown. The only
part worth automating is the bookkeeping, which is the slug, the manifest
entry, and the image folder.

Standard library only, so `uv run` needs to install nothing.
"""

import argparse
import html
import shutil
import json
import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent
POSTS = ROOT / "site" / "content" / "posts"
MANIFEST = POSTS / "index.json"
IMAGES = ROOT / "site" / "assets" / "posts"
SITEMAP = ROOT / "site" / "sitemap.xml"
BLOG_TEMPLATE = ROOT / "site" / "blog" / "index.html"
GENERATED_MARK = "<!-- GENERATED by newpost.py from site/blog/index.html. Do not edit: rerun `newpost.py check`. -->"
BASE_URL = "https://luisamunoz.com"
WORDS_PER_MINUTE = 220

STARTER = """Open with the thing the reader already feels. Not what you built, what they'd
recognize. Then get to the point.

## A section

Write. Delete this scaffolding as you go.

Images go in `site/assets/posts/{slug}/`. Reference them like this, and the
relative path resolves correctly from /blog/:

```
![what it shows](../assets/posts/{slug}/screenshot.png)
```

Stop when the point is made.
"""

# Image checks ignore anything inside a fenced block, so an example in a post
# about writing posts doesn't get reported as a broken image.
RE_FENCED = re.compile(r"^```.*?^```", re.S | re.M)


def slugify(text: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return s or "untitled"


def load_manifest() -> dict:
    if not MANIFEST.exists():
        return {"posts": []}
    try:
        return json.loads(MANIFEST.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        sys.exit(f"index.json is not valid JSON ({e}). Fix it before running this.")


def save_manifest(data: dict) -> None:
    MANIFEST.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def read_minutes(body: str) -> int:
    # Rough on purpose. Fenced code reads slower than prose, but nobody has ever
    # been misled by a read time being one minute off.
    return max(1, round(len(body.split()) / WORDS_PER_MINUTE))


def cmd_new(args: argparse.Namespace) -> None:
    # --slug goes through slugify too. Taking it raw let "Not A Slug!!" become
    # a real filename and a real manifest entry, which then can't be served.
    slug = slugify(args.slug) if args.slug else slugify(args.title)
    md = POSTS / f"{slug}.md"
    data = load_manifest()

    if any(p.get("slug") == slug for p in data["posts"]) or md.exists():
        sys.exit(f"'{slug}' already exists. Pick another title, or pass --slug.")

    POSTS.mkdir(parents=True, exist_ok=True)
    img_dir = IMAGES / slug
    img_dir.mkdir(parents=True, exist_ok=True)
    # git won't track an empty directory, so give it something to hold on to
    (img_dir / ".gitkeep").touch()

    md.write_text(STARTER.format(slug=slug), encoding="utf-8")

    entry = {
        "slug": slug,
        "title": args.title,
        "date": args.date or date.today().isoformat(),
        "category": args.category,
        "minutes": read_minutes(md.read_text(encoding="utf-8")),
        "summary": args.summary,
        "tags": [t.strip() for t in args.tags.split(",") if t.strip()] if args.tags else [],
    }
    if args.draft:
        entry["draft"] = True

    data["posts"].insert(0, entry)
    save_manifest(data)

    rel = md.relative_to(ROOT)
    if not args.draft:
        live = [x for x in data["posts"] if x.get("slug") and not x.get("draft")]
        for path in write_post_pages(live):
            print(f"  created  {path.relative_to(ROOT)}")
        write_sitemap(live)
    print(f"  created  {rel}")
    print(f"  created  {img_dir.relative_to(ROOT)}/")
    print(f"  updated  {MANIFEST.relative_to(ROOT)}")
    print()
    print("  next:")
    print(f"    1. write it            {rel}")
    print("    2. fill in the summary  site/content/posts/index.json")
    print("    3. preview              Live Server -> site/blog/")
    print("    4. read time + checks   uv run newpost.py check")
    if args.draft:
        print("\n  marked as a draft, so it stays off the site until you remove that flag.")


def post_url(slug: str) -> str:
    return f"{BASE_URL}/blog/{slug}/"


def render_post_page(template: str, post: dict) -> str:
    """One real HTML file per post, so its title, description and share card
    are in the HTML a crawler or a link unfurler actually receives. blog.js
    patches these at runtime too, but LinkedIn and Slack never run it.

    The page is the blog template with <base href="../"> added first in
    <head>. Every relative URL in the template -- the stylesheet, the scripts,
    the markdown fetch, image paths written as ../assets/... in a post --
    then resolves exactly as it does from /blog/. One template, one renderer.
    """
    slug = post["slug"]
    title = html.escape(f"{post.get('title') or slug} · Luis A. Munoz", quote=True)
    desc = html.escape(post.get("summary") or "", quote=True)
    url = post_url(slug)
    out = template

    def sub(pattern: str, repl: str, count: int = 1) -> None:
        nonlocal out
        new, n = re.subn(pattern, repl, out, count=count, flags=re.S)
        if n != count:
            sys.exit(f"blog template changed shape: {pattern!r} matched {n}x, expected {count}")
        out = new

    # <base> must precede every relative URL, so it goes right after the charset.
    sub(r'(<meta charset="utf-8" />)', r'\1\n    ' + GENERATED_MARK + r'\n    <base href="../" />')
    sub(r"<title>.*?</title>", f"<title>{title}</title>")
    sub(r'(name="description"\s+content=")[^"]*(")', rf"\g<1>{desc}\g<2>")
    sub(r'(<link rel="canonical" href=")[^"]*(")', rf"\g<1>{url}\g<2>")
    sub(r'(property="og:type" content=")[^"]*(")', r"\g<1>article\g<2>")
    sub(r'(property="og:url" content=")[^"]*(")', rf"\g<1>{url}\g<2>")
    sub(r'(property="og:title" content=")[^"]*(")', rf"\g<1>{title}\g<2>")
    sub(r'(property="og:description"\s+content=")[^"]*(")', rf"\g<1>{desc}\g<2>")
    sub(r'(name="twitter:title" content=")[^"]*(")', rf"\g<1>{title}\g<2>")
    sub(r'(name="twitter:description"\s+content=")[^"]*(")', rf"\g<1>{desc}\g<2>")
    # With <base href="../">, "#main" would resolve to /blog/#main and LEAVE the
    # page. Pointing it at this post's own path keeps it an in-page jump.
    sub(r'href="#main"', f'href="{slug}/#main"')
    # blog.js reads the slug from here when there's no ?p= in the URL.
    sub(r'<div id="blog-root"', f'<div id="blog-root" data-slug="{html.escape(slug, quote=True)}"')
    return out


def write_post_pages(posts: list) -> list:
    """Write site/blog/<slug>/index.html for every live post, and remove pages
    this script generated for posts that are no longer live. Returns the
    paths it changed, so `check` can report them and stay idempotent."""
    template = BLOG_TEMPLATE.read_text(encoding="utf-8")
    changed, live = [], set()
    for post in posts:
        slug = post.get("slug")
        if not slug:
            continue
        live.add(slug)
        page = BLOG_TEMPLATE.parent / slug / "index.html"
        body = render_post_page(template, post)
        if not page.exists() or page.read_text(encoding="utf-8") != body:
            page.parent.mkdir(parents=True, exist_ok=True)
            page.write_text(body, encoding="utf-8")
            changed.append(page)
    # Only ever delete directories this script made -- never hand-made ones.
    for d in BLOG_TEMPLATE.parent.iterdir():
        idx = d / "index.html"
        if d.is_dir() and d.name not in live and idx.exists() and GENERATED_MARK in idx.read_text(encoding="utf-8"):
            shutil.rmtree(d)
            changed.append(d)
    return changed


def write_sitemap(posts: list) -> bool:
    """Regenerate site/sitemap.xml from the manifest.

    Generated rather than hand-maintained for the same reason index.json is the
    manifest: a file you have to remember to update is a file that goes stale,
    and a stale sitemap points crawlers at posts that don't exist.

    Post URLs are the generated /blog/<slug>/ pages. /blog/?p=<slug> still
    works for old links, but its canonical points here.
    """
    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']

    newest = max((str(p.get("date", "")) for p in posts), default="")

    def url(loc: str, lastmod: str = "", priority: str = "") -> None:
        lines.append("  <url>")
        lines.append(f"    <loc>{loc}</loc>")
        if lastmod:
            lines.append(f"    <lastmod>{lastmod}</lastmod>")
        if priority:
            lines.append(f"    <priority>{priority}</priority>")
        lines.append("  </url>")

    url(f"{BASE_URL}/", newest, "1.0")
    url(f"{BASE_URL}/blog/", newest, "0.8")
    for post in posts:
        slug = post.get("slug")
        if slug:
            url(post_url(slug), str(post.get("date", "")), "0.6")

    lines.append("</urlset>")
    out = "\n".join(lines) + "\n"

    previous = SITEMAP.read_text(encoding="utf-8") if SITEMAP.exists() else ""
    if out == previous:
        return False
    SITEMAP.write_text(out, encoding="utf-8")
    return True


def cmd_check(args: argparse.Namespace) -> None:
    data = load_manifest()
    problems = []
    changed = False

    seen = set()
    for p in data["posts"]:
        slug = p.get("slug")
        where = slug or "<entry with no slug>"

        if not slug:
            problems.append("an entry has no slug")
            continue
        if slug in seen:
            problems.append(f"{where}: duplicate slug")
        seen.add(slug)

        md = POSTS / f"{slug}.md"
        if not md.exists():
            problems.append(f"{where}: no matching {slug}.md")
            continue

        for field in ("title", "date", "summary"):
            if not p.get(field):
                problems.append(f"{where}: {field} is empty")
        if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", str(p.get("date", ""))):
            problems.append(f"{where}: date should be YYYY-MM-DD")
        if not p.get("category"):
            problems.append(f"{where}: no category, so it won't show under a filter")

        body = md.read_text(encoding="utf-8")
        actual = read_minutes(body)
        if p.get("minutes") != actual:
            print(f"  read time  {slug}: {p.get('minutes')} -> {actual}")
            p["minutes"] = actual
            changed = True

        # catch images referenced by a post that aren't actually there
        for src in re.findall(r"!\[[^\]]*\]\(([^)\s]+)\)", RE_FENCED.sub("", body)):
            if src.startswith(("http://", "https://", "//")):
                continue
            # Posts are viewed at /blog/, so relative paths resolve from there.
            # A leading slash means the site root, and joining that with pathlib
            # would jump to the filesystem root instead, so strip it first.
            base = ROOT / "site" if src.startswith("/") else ROOT / "site" / "blog"
            target = (base / src.lstrip("/")).resolve()
            if not target.exists():
                problems.append(f"{where}: image not found -> {src}")

    # files on disk with no manifest entry are invisible to the site
    for md in sorted(POSTS.glob("*.md")):
        if md.stem not in seen:
            problems.append(f"{md.name}: on disk but not in index.json, so nothing links to it")

    if changed:
        save_manifest(data)
        print(f"  updated  {MANIFEST.relative_to(ROOT)}")

    # Only the posts the site actually shows: no drafts, newest first.
    live = sorted(
        (p for p in data["posts"] if p.get("slug") and not p.get("draft")),
        key=lambda p: str(p.get("date", "")), reverse=True,
    )
    for path in write_post_pages(live):
        print(f"  updated  {path.relative_to(ROOT)}")
    if write_sitemap(live):
        print(f"  updated  {SITEMAP.relative_to(ROOT)}")

    print()
    if problems:
        print(f"  {len(problems)} thing(s) to fix:")
        for p in problems:
            print(f"    - {p}")
        sys.exit(1)
    print(f"  {len(data['posts'])} post(s), all clean.")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    new = sub.add_parser("new", help="scaffold a post: markdown file, image folder, manifest entry")
    new.add_argument("title")
    new.add_argument("-c", "--category", default="building", help="default: building")
    new.add_argument("-t", "--tags", default="", help="comma-separated")
    new.add_argument("-s", "--summary", default="", help="the card blurb, can be filled in later")
    new.add_argument("--slug", default="", help="override the slug derived from the title")
    new.add_argument("--date", default="", help="YYYY-MM-DD, defaults to today")
    new.add_argument("--draft", action="store_true", help="keep it off the site for now")
    new.set_defaults(func=cmd_new)

    chk = sub.add_parser("check", help="validate the manifest, refresh read times, rebuild post pages and sitemap.xml")
    chk.set_defaults(func=cmd_check)

    args = ap.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
